//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HumaneSociety.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.4.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
<<<<<<< HEAD
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-THG6VQ2;Initial Catalog=HumaneSociety;Integrated Security=True" +
            ";Connect Timeout=30;Encrypt=False;TrustServerCertificate=False")]
        public string HumaneSocietyConnectionString {
            get {
                return ((string)(this["HumaneSocietyConnectionString"]));
=======
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=RYANHOLMAN75A5\\SQLEXPRESS;Initial Catalog=HumaneSociety;Integrated Se" +
            "curity=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False")]
        public string HumaneSocietyConnectionString {
            get {
                return ((string)(this["HumaneSocietyConnectionString"]));
>>>>>>> e95805d5d58d95f07e680d3cc0115d80818c45f0
            }
        }
    }
}
